
skillMetadata:
  sections:
    - name: Summarization micro-service
      fields:
        - type: label
          label: Use this API token to allow other applications to send web page URLs to the Summarization micro-service.
        - name: api_token
          type: text
          label: API Token
          value:
        - type: label
          label: Use this Root CA Certificate to allow other applications to connect to the Summarization micro-service over an encrypted connection.
        - name: root_ca
          type: text
          label: Root CA Certificate
          value:
