
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: summarization_ratio
          type: number
          label: Summarization Ratio
          value: "0.2"
          placeholder: Fraction (percentage) of the original text that should be part of the summary. Enter a number between 0.0 and 1.0, exclusive of these two numbers. This setting will be applied to new web pages only.
